--[[
    init.lua
    Created: 03/03/2025 16:08:19
    Description: Autogenerated script file for the map old_buesares_sealed.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local old_buesares_sealed = {}

-------------------------------
-- Map Callbacks
-------------------------------
---old_buesares_sealed.Init(map)
--Engine callback function
function old_buesares_sealed.Init(map)


end

---old_buesares_sealed.Enter(map)
--Engine callback function
function old_buesares_sealed.Enter(map)

  GAME:FadeIn(20)

end

---old_buesares_sealed.Exit(map)
--Engine callback function
function old_buesares_sealed.Exit(map)


end

---old_buesares_sealed.Update(map)
--Engine callback function
function old_buesares_sealed.Update(map)


end

---old_buesares_sealed.GameSave(map)
--Engine callback function
function old_buesares_sealed.GameSave(map)


end

---old_buesares_sealed.GameLoad(map)
--Engine callback function
function old_buesares_sealed.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return old_buesares_sealed

