--[[
    init.lua
    Created: 03/01/2025 15:39:30
    Description: Autogenerated script file for the map aura_shrine.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local aura_shrine = {}

-------------------------------
-- Map Callbacks
-------------------------------
---aura_shrine.Init(map)
--Engine callback function
function aura_shrine.Init(map)


end

---aura_shrine.Enter(map)
--Engine callback function
function aura_shrine.Enter(map)

  GAME:FadeIn(20)

end

---aura_shrine.Exit(map)
--Engine callback function
function aura_shrine.Exit(map)


end

---aura_shrine.Update(map)
--Engine callback function
function aura_shrine.Update(map)


end

---aura_shrine.GameSave(map)
--Engine callback function
function aura_shrine.GameSave(map)


end

---aura_shrine.GameLoad(map)
--Engine callback function
function aura_shrine.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return aura_shrine

