--[[
    init.lua
    Created: 02/15/2025 08:15:53
    Description: Autogenerated script file for the map a_oran_tavern.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local a_oran_tavern = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---a_oran_tavern.Init(zone)
--Engine callback function
function a_oran_tavern.Init(zone)


end

---a_oran_tavern.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function a_oran_tavern.EnterSegment(zone, rescuing, segmentID, mapID)


end

---a_oran_tavern.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function a_oran_tavern.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---a_oran_tavern.Rescued(zone, name, mail)
--Engine callback function
function a_oran_tavern.Rescued(zone, name, mail)


end

return a_oran_tavern

