--[[
    init.lua
    Created: 02/08/2025 15:48:32
    Description: Autogenerated script file for the map oran_tavern.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local oran_tavern = {}

-------------------------------
-- Map Callbacks
-------------------------------
---oran_tavern.Init(map)
--Engine callback function
function oran_tavern.Init(map)


end

---oran_tavern.Enter(map)
--Engine callback function
function oran_tavern.Enter(map)

  GAME:FadeIn(20)

end

---oran_tavern.Exit(map)
--Engine callback function
function oran_tavern.Exit(map)


end

---oran_tavern.Update(map)
--Engine callback function
function oran_tavern.Update(map)


end

---oran_tavern.GameSave(map)
--Engine callback function
function oran_tavern.GameSave(map)


end

---oran_tavern.GameLoad(map)
--Engine callback function
function oran_tavern.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return oran_tavern

