--[[
    init.lua
    Created: 02/08/2025 15:48:32
    Description: Autogenerated script file for the map oran_tavern.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'tsi_pmdo.GeneralFunctions'

-- Package name
local oran_tavern = {}

-------------------------------
-- Map Callbacks
-------------------------------
---oran_tavern.Init(map)
--Engine callback function
function oran_tavern.Init(map)


end

---oran_tavern.Enter(map)
--Engine callback function
function oran_tavern.Enter(map)

  local player = CH('PLAYER')

  GeneralFunctions.DeeshSetPlayer()

  --Player always 'enters' the map either via the intro scene or a new day, so this is an easy if statement
  if SV.a_oran_tavern.IntroSeen then
    oran_tavern.NewDayScene()
  else
    oran_tavern.IntroScene()
  end

end

---oran_tavern.Exit(map)
--Engine callback function
function oran_tavern.Exit(map)


end

---oran_tavern.Update(map)
--Engine callback function
function oran_tavern.Update(map)


end

---oran_tavern.GameSave(map)
--Engine callback function
function oran_tavern.GameSave(map)


end

---oran_tavern.GameLoad(map)
--Engine callback function
function oran_tavern.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Cutscene Functions
-------------------------------

function oran_tavern.IntroScene(map)

  GAME:FadeIn(20)

  UI:WaitShowDialogue("Oran Tavern intro scene in this function.")

  --Set player money to 2k

  _DATA.Save.ActiveTeam.Money = 2000

  SV.a_oran_tavern.IntroSeen = true

  GAME:CutsceneMode(false)

end

function oran_tavern.NewDayScene(map)

  GAME:FadeIn(20)

  --Set player money to 2k

  _DATA.Save.ActiveTeam.Money = 2000

  --Reset all party members to level 1, reset skills, and clear any boosts.

  UI:WaitShowDialogue("Oran Tavern new day scene in this function.")
  
  GAME:CutsceneMode(false)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function oran_tavern.Board_Action(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker()
  SOUND:PlaySE("Menu/Skip")
  UI:AssemblyMenu()
  UI:WaitForChoice()
  result = UI:ChoiceResult()
end

return oran_tavern

