--[[
    init.lua
    Created: 03/03/2025 16:08:19
    Description: Autogenerated script file for the map old_buesares_clean.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local old_buesares_clean = {}

-------------------------------
-- Map Callbacks
-------------------------------
---old_buesares_clean.Init(map)
--Engine callback function
function old_buesares_clean.Init(map)


end

---old_buesares_clean.Enter(map)
--Engine callback function
function old_buesares_clean.Enter(map)

  GAME:FadeIn(20)

end

---old_buesares_clean.Exit(map)
--Engine callback function
function old_buesares_clean.Exit(map)


end

---old_buesares_clean.Update(map)
--Engine callback function
function old_buesares_clean.Update(map)


end

---old_buesares_clean.GameSave(map)
--Engine callback function
function old_buesares_clean.GameSave(map)


end

---old_buesares_clean.GameLoad(map)
--Engine callback function
function old_buesares_clean.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return old_buesares_clean

