--[[
    init.lua
    Created: 03/03/2025 16:08:19
    Description: Autogenerated script file for the map old_buesares.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local old_buesares = {}

-------------------------------
-- Map Callbacks
-------------------------------
---old_buesares.Init(map)
--Engine callback function
function old_buesares.Init(map)


end

---old_buesares.Enter(map)
--Engine callback function
function old_buesares.Enter(map)

  GAME:FadeIn(20)

end

---old_buesares.Exit(map)
--Engine callback function
function old_buesares.Exit(map)


end

---old_buesares.Update(map)
--Engine callback function
function old_buesares.Update(map)


end

---old_buesares.GameSave(map)
--Engine callback function
function old_buesares.GameSave(map)


end

---old_buesares.GameLoad(map)
--Engine callback function
function old_buesares.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return old_buesares

