--[[
    init.lua
    Created: 03/01/2025 16:24:52
    Description: Autogenerated script file for the map a_the_dungeon.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local a_the_dungeon = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---a_the_dungeon.Init(zone)
--Engine callback function
function a_the_dungeon.Init(zone)


end

---a_the_dungeon.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function a_the_dungeon.EnterSegment(zone, rescuing, segmentID, mapID)


end

---a_the_dungeon.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function a_the_dungeon.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---a_the_dungeon.Rescued(zone, name, mail)
--Engine callback function
function a_the_dungeon.Rescued(zone, name, mail)


end

return a_the_dungeon

