--[[
    init.lua
    Created: 02/08/2025 18:21:25
    Description: Autogenerated script file for the map intro_map.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local intro_map = {}

-------------------------------
-- Map Callbacks
-------------------------------
---intro_map.Init(map)
--Engine callback function
function intro_map.Init(map)


end

---intro_map.Enter(map)
--Engine callback function
function intro_map.Enter(map)

  GAME:FadeIn(20)

end

---intro_map.Exit(map)
--Engine callback function
function intro_map.Exit(map)


end

---intro_map.Update(map)
--Engine callback function
function intro_map.Update(map)


end

---intro_map.GameSave(map)
--Engine callback function
function intro_map.GameSave(map)


end

---intro_map.GameLoad(map)
--Engine callback function
function intro_map.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return intro_map

